- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Upload NGINX config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/horizonalerts.conf
  notify: restart nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/horizonalerts.conf
    dest: /etc/nginx/sites-enabled/horizonalerts.conf
    state: link
  notify: restart nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Ensure NGINX running
  service:
    name: nginx
    state: started
    enabled: true
